name: detekt
on: [ push, pull_request ]
jobs:
    detekt:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout
                uses: actions/checkout@v3

            -   name: Setup JDK
                uses: actions/setup-java@v3
                with:
                    distribution: oracle
                    java-version: '17'

            -   name: Grant execute permission for gradlew
                run: chmod +x gradlew

            -   name: Run detekt
                run: ./gradlew detekt
